### ISSUE TITLE
7.20

### ISSUE THREAD

**Issue by AymaxLi** [2016-TopView-FrontEnd/JavaScript-Learning#12]
## Today I learned
- 高设的BOM和一部分DOM
- 完成了codeschool的TryjQuery
## Any Questions
- 暂无
## Schedule of Tomorrow
- 继续推进高设，开始填this的坑
## How I Feel Right Now
- better than yesterday

**Comment by jermyn626** [comment]
## Today I learned
- BOM 和 部分DOM
- 看了下mvc，什么鬼啊看不懂啊

## Any Questions
- 不大明白究竟前端怎么打mvc，跟后台那些又有哪些区别，数据那些怎么交接

## Schedule of Tomorrow
- 看剩下的DOM
- 继续推高设
- 继续了解 mvc 吧

## How I Feel Right Now
- 今天睡过头了，bad bad的，闹钟设一个可能不够 :{

**Comment by RonkTsang** [comment]
## Today I learned
- 高设的BOM 、DOM部分
- 稍微看了下闭包的文章

## Any Questions
- 暂无

## Schedule of Tomorrow
- 学习codeschool
- 继续看《高设》

## How I Feel Right Now
- 还行吧

**Comment by kimZLeung** [comment]
## Today I learned
- 高设的第十章和部分第十一章的内容
- 完成了code school的JQuery部分

## Any Questions
- 暂无

## Schedule of Tomorrow
- 继续推进高设十一章的内容
- 看一下JQuery

## How I Feel Right Now
- 还OK吧

**Comment by HwangJianyi** [comment]
## Today I learned
- DOM
- JQuery

## Any Questions
- 无

## Schedule of Tomorrow
- 继续看完JQuery
- 看高设

## How I Feel Right Now
- 网速真慢

**Comment by JoeBBChen** [comment]
@jermyn626 
曾经，我为了起床预习考试，我设了8个闹钟，不要问我最终起床了没，用心感受我要起床的决心就好
 :simple_smile:

**Comment by JoeBBChen** [comment]
@jermyn626  还有我远成老大，为了起床，跟室友打赌，起不来就给室友10块，成就了我远成老大今天技术的牛掰，所以你起不来，给我们10块买西瓜吧
