### ISSUE TITLE
7.31

### ISSUE THREAD

**Issue by RonkTsang** [2016-TopView-FrontEnd/JavaScript-Learning#23]
## Today I learned
- 改todo
## Any Questions
- 阿贾克斯什么鬼、怎么用，去看看
## Schedule of Tomorrow
- 学习下师姐今晚分享的内容
- 完善todo
## How I Feel Right Now
- 还行

**Comment by HwangJianyi** [comment]
## Today I learned
- todo-css

## Any Questions
- ajks?

## Schedule of Tomorrow
- todotodotodoAjax

## How I Feel Right Now
- 😈

**Comment by kimZLeung** [comment]
## Today I learned
- 重构了一下todo

## Any Questions
- 不会Ajax

## Schedule of Tomorrow
- 继续完成todo，尝试看一下Ajax

## How I Feel Right Now
- :jack_o_lantern:
