### ISSUE TITLE
#8.1

### ISSUE THREAD

**Issue by AymaxLi** [2016-TopView-FrontEnd/JavaScript-Learning#25]
## Today I learned
- 看了昨天分享会的内容
- 高设21章ajax
## Any Questions
- 暂无
## Schedule of Tomorrow
- 继续学ajax
## How I Feel Right Now
- :cyclone: :cyclone:

**Comment by RonkTsang** [comment]
## Today I learned
- 修复了todo的已知bug
- 看了下高设中的Ajax

## Any Questions
- 暂无

## Schedule of Tomorrow
- 继续学Ajax

## How I Feel Right Now
- :cyclone: :weary:

**Comment by kimZLeung** [comment]
## Today I learned
- 完善了一下自己的todo
- 昨晚的bug自己也了解了一下

## Any Questions
- 暂无

## Schedule of Tomorrow
- 看高设的ajax，虽然看得比较懵

## How I Feel Right Now
- :cyclone: :cyclone: :cyclone:

**Comment by jermyn626** [comment]
## Today I learned
- Ajax

## Any Questions
- 暂无

## Schedule of Tomorrow
- todo实现读取JSON文件
- 看高设

## How I Feel Right Now
- :D

**Comment by HwangJianyi** [comment]
## Today I learned
- 做完todo的功能和改掉遗留问题，因为用了绝对定位，对屏幕宽度做了适应

## Any Questions
- no

## Schedule of Tomorrow
- 暴雨中ajax

## How I Feel Right Now
- too late
