### ISSUE TITLE
7.13

### ISSUE THREAD

**Issue by AymaxLi** [2016-TopView-FrontEnd/JavaScript-Learning#4]
# What I learn
- 看了高设第四章，还差一点看完（看完感觉自己懵懵哒）
  笔记： [第四章](https://www.zybuluo.com/aymax/note/435354)
- 刷了部分 Basic JavaScript
# Quesction & Sulotion

高设 P75 为什么 `buildUrl()` 可以访问到 `with()` 里面的url

```
function buildUrl() {
    var qs = "?debug=true";  
        with(location){
            var url = href + qs;
        }
    return url;
    }
}
```

请教了坚神后才知道，解析这个 `buildUrl()` 的时候，`with()` 里面的 `var url` 是在 `buildUrl()` 的活动对象里面的，所以 `buildUrl()` 可以访问到 `with()` 里面的 `url`。

解决了这个问题之后，我们发现坚神昨天提的问题和这个类似，所以顺便讨论了昨天坚神的 issue

```
var scope="global";
function t(){
console.log( '1 ' + scope);      // 1 undefined
var scope="local"
console.log( '2 ' + scope);      // 2 local
}
t();
console.log( '3 ' + scope);      // 3 global
```

经过大家讨论之后得出，因为解析 `t()` 的时候，会把 `var scope` 添加到 `t()` 的活动对象里面，不过**还没初始化**，所以是 `undefined`，所以执行第一个 `console` 的时候是 `undefined` ，执行到第4行的时候对`scope` 赋值了 "local" ，所以第二个`console` 会输出 "local"，执行完 `t()` 之后，`t()` 的局部执行环境里的变量会被销毁，所以第三个 `console` 输出的是 "global"
# Schedule for Tomorrow
- 看完高设第四章  开第五章
- 继续完成Basic JavaScript

**Comment by jermyn626** [comment]
### What I learn
- 完成了FreeCodeCamp `Basic JavaScript` 后半部分
- [JavaScript高级程序设计-第四章](https://www.zybuluo.com/jermyn626/note/435187)
- JavaScript 高级程序设计- 第六章6.2一半

### Report
- JavaScript 高级程序设计- 第六章6.2一半
- FreeCodeCamp Responsive Design with Bootstrap 部分还没动

**Comment by kimZLeung** [comment]
# What I learn
- 暂时性放下第五章。看了第四章。
- 继续完成了CodeCamp的Basic JavaScript的一部分

# Quesction
- 对于第四章的利用with语句或者try...catch语句延长作用域链不理解，with语句会多创建出一个作用域吗？

# Solution
- 自己上网查了查，也问了问身边的小伙伴，还是不大了解。只清楚加了with语句之后with引用的对象的属性会提前放到作用域链的前端。

# 明日计划
- 对第四章加深了解，学习第六章。
- 继续完成Basic JavaScript部分的题目。

**Comment by HwangJianyi** [comment]
# What I Learn
- 今天发现昨天发的issue被改了，所以把那个提升的给看了，结合自己前天看了的部分作用域链的知识和几篇帖子，算是理解了它们的运作过程。
- 今天把师姐推的那个array和object的文档看了前面一部分，因为全是英文，过程异常艰难。
- codecamp上做题、练习。

# Question & Solution
- 函数提示那部分还是有点看不懂的，因为网上给的例子里的那些函数长得太抽象，等我看完function类型再去看一下。
- codecamp里的题目有点搞不懂它们存在意义，在杰神的指导下，开始有点理解它们到底想教我做什么。

# Schedule for Tomorrow
- 上午把codecamp里的Bootstrap指导的那部分做完。
- 把第5章推完

**Comment by RonkTsang** [comment]
# What I Learn
- 做完FreeCodeCamp的Basic JavaScript
- 看了第五章一部分

# Question & Solution
- 重新看了有关 作用域链 的内容，但好像只是稍稍理解
- 昨天的issue：
  input标签中type="submit" 和button标签 type="submit" 在表单中都可以提交！

# Schedule for Tomorrow
- 继续高设的第五章
- codecamp 进入下一部分
